### ISSUE TITLE
TODO list for later

### ISSUE THREAD

**Issue by StephenIsTaken** [StephenIsTaken/Raven-BPlusPlusPlus#10]
We should add these when we make it a blatant client:
[+] Add Hypixel Nuker
[+] Legit Scaffold
[+] AutoSniper for Hypixel
[+] Hypixel NoSlow and AutoBlock
[+] BHop bypasses

**Comment by Cosmic-SC** [comment]
yeah lmao sure (real btw 100% trust)

**Comment by Cosmic-SC** [comment]
probably wont add anyone of these

**Comment by StephenIsTaken** [comment]
> probably wont add anyone of these

Np i can still skid

**Comment by Cosmic-SC** [comment]
just close this or add to main todo list
