### ISSUE TITLE
Downloading updates

### ISSUE THREAD

**Issue by Darkmonkey55** [StephenIsTaken/Raven-BPlusPlusPlus#14]
So @Cosmic-SC  said there are downloads in the builds but not in #releases...? I dont really use github could anyone show me how to download the mini updates thingies or whatever?

**Comment by Cosmic-SC** [comment]
no? I said that If you want to play on the latest version always then just build the jar yourself from the src

**Comment by Cosmic-SC** [comment]
or apply for BETA role in dc/ask @StephenIsTaken

**Comment by chs12345** [comment]
I downloaded gradle and opened project, how can I build the jar?

**Comment by chs12345** [comment]
also should I open with maven or gradle?

**Comment by Darkmonkey55** [comment]
> no? I said that If you want to play on the latest version always then just build the jar yourself from the src

ohh right ok sorry mb... how do u build a jar urself? is it difficult? i dont have coding experience.

dont have dc :(

**Comment by Cosmic-SC** [comment]
well... just setup gradle, get java jdk 8 & gradlew build on cmd or use some build script
