### ISSUE TITLE
Added Movefix better be silent

### ISSUE THREAD

**Issue by SpaceLightningExpress** [StephenIsTaken/Raven-BPlusPlusPlus#15]
Movefix good for future ac like polar and grim

**Comment by Cosmic-SC** [comment]
whats the point anyways? silent and strict both do the same thing

**Comment by Cosmic-SC** [comment]
> Movefix good for future ac like polar and grim

? movefix is already implemented in killaura

**Comment by SpaceLightningExpress** [comment]
> Collaborator

strict is very annoying even on bedwars when u do pvp 1 v 1 on 1 block bridge u just fall and die

**Comment by Cosmic-SC** [comment]
strict movefix is better for anticheats like polar and intave idk if silent bypasses anyways

**Comment by SpaceLightningExpress** [comment]
> strict movefix is better for anticheats like polar and intave idk if silent bypasses anyways

it bypass just look augustus and eject it has silent move fix and they bypass intave and polar

**Comment by Cosmic-SC** [comment]
idk maybe ill add after im done with stuff in todo list
