### ISSUE TITLE
Errors after following the steps to setup the workspace.

### ISSUE THREAD

**Issue by ImmortalLeaf101** [StephenIsTaken/Raven-BPlusPlusPlus#19]
So after setting up the workspace, I'm facing a few errors. I'm using JDK 8.
![image](https://github.com/StephenIsTaken/Raven-BPlusPlusPlus/assets/100413928/5e26f5ae-8fd9-4d74-8109-81f8acf9e805)

**Comment by Cosmic-SC** [comment]
u messed up ur workspace
the minecraft source is not properly installed hence the reason it is throwing errors on minecraft code

**Comment by ImmortalLeaf101** [comment]
Fixed, sorry for wasting your time.

**Comment by Cosmic-SC** [comment]
np :)
