### ISSUE TITLE
TODO list:

### ISSUE THREAD

**Issue by StephenIsTaken** [StephenIsTaken/Raven-BPlusPlusPlus#20]
[+] TargetHud
Smth like this: https://youtu.be/Lw6l_QofjpI
[+] New Sliders
[=] Working Nuker (Maybe)
[+] Silent Strafe
[+] Circle TargetESP

**Comment by Cosmic-SC** [comment]
blatant client huh?

**Comment by Cosmic-SC** [comment]
anyways good luck!

**Comment by cubigiabinh** [comment]
@StephenIsTaken I honestly love the classic ClickGUI from RavenB+ or Raven, and I'd be appreciated if you bring the old ClickGUI again.

**Comment by StephenIsTaken** [comment]
> @StephenIsTaken I honestly love the classic ClickGUI from RavenB+ or Raven, and I'd be appreciated if you bring the old ClickGUI again.

Make it yourself with the custom clickgui

**Comment by Cosmic-SC** [comment]
[+] Update Aura with the "SpecialEvent" :)))))))))

**Comment by StephenIsTaken** [comment]
[+] Make Aura not target though walls

**Comment by Cosmic-SC** [comment]
eh ok

**Comment by neilhuang007** [comment]
can you discribe the target esp ? mabye i could do it for you

**Comment by StephenIsTaken** [comment]
> 

like sigma has that circle around players

**Comment by neilhuang007** [comment]
ahhh, like liquidbounce reborn, the scan effect??

**Comment by StephenIsTaken** [comment]
> ahhh, like liquidbounce reborn, the scan effect??

ig

**Comment by neilhuang007** [comment]
ok check out this respository and playeresp https://github.com/neilhuang007/omegahack it has the effect on it
