### ISSUE TITLE
LeftClicker Bugs

### ISSUE THREAD

**Issue by LoLiSDLSDL** [StephenIsTaken/Raven-BPlusPlusPlus#31]
LeftClicker can't break blocks in Multiplayer Servers when "Break Blocks" on

**Comment by Cosmic-SC** [comment]
![image](https://github.com/StephenIsTaken/Raven-BPlusPlusPlus/assets/133380776/b6b57d96-1de0-4763-9ed6-e2d6df45a53a)
have a great day!

**Comment by StephenIsTaken** [comment]
> LeftClicker can't break blocks in Multiplayer Servers when "Break Blocks" on

skill issue !
