### ISSUE TITLE
Updates.

### ISSUE THREAD

**Issue by Darkmonkey55** [StephenIsTaken/Raven-BPlusPlusPlus#32]
I saw a yt vid from someone i cant remmeber who but it was using 2.0 version of this...? were they lying or smt or idk cuz this is 1.4. are tjhere gonna be any more updates?

**Comment by StephenIsTaken** [comment]
> I saw a yt vid from someone i cant remmeber who but it was using 2.0 version of this...? were they lying or smt or idk cuz this is 1.4. are tjhere gonna be any more updates?

zmixins is a faggot the latest version is 1.5 in the discord server

**Comment by Darkmonkey55** [comment]
ohh ok yeah right... why is that guy a faggot? ratted it ro smt? also i dont have discord is there a way to access 1.5 pls

**Comment by Cosmic-SC** [comment]
> I saw a yt vid from someone i cant remmeber who but it was using 2.0 version of this...? were they lying or smt or idk cuz this is 1.4. are tjhere gonna be any more updates?

maybe there will be updates in the future (from next year hopefully) but cannot guarantee anything right now

**Comment by Darkmonkey55** [comment]
> > I saw a yt vid from someone i cant remmeber who but it was using 2.0 version of this...? were they lying or smt or idk cuz this is 1.4. are tjhere gonna be any more updates?
> 
> maybe there will be updates in the future (from next year hopefully) but cannot guarantee anything right now

ok cool thanks, can u send me a download link to the 1.5 latest that @StephenIsTaken mentioned please. I dont have discord though.

**Comment by Cosmic-SC** [comment]
> > > I saw a yt vid from someone i cant remmeber who but it was using 2.0 version of this...? were they lying or smt or idk cuz this is 1.4. are tjhere gonna be any more updates?
> > 
> > 
> > maybe there will be updates in the future (from next year hopefully) but cannot guarantee anything right now
> 
> ok cool thanks, can u send me a download link to the 1.5 latest that @StephenIsTaken mentioned please. I dont have discord though.

just make a temp account and download it 1.5 is just a buggy update imo it just adds targethud and flaggy scaffold use 1.3 or 1.4

**Comment by Darkmonkey55** [comment]
> > > > I saw a yt vid from someone i cant remmeber who but it was using 2.0 version of this...? were they lying or smt or idk cuz this is 1.4. are tjhere gonna be any more updates?
> > > 
> > > 
> > > maybe there will be updates in the future (from next year hopefully) but cannot guarantee anything right now
> > 
> > 
> > ok cool thanks, can u send me a download link to the 1.5 latest that @StephenIsTaken mentioned please. I dont have discord though.
> 
> just make a temp account and download it 1.5 is just a buggy update imo it just adds targethud and flaggy scaffold use 1.3 or 1.4

oh ok cool thanks, idk if yk any good clients i can use that r like ghost clients yk with decent visuals, cuz like nightx is shit asf and no other ghost clients have good features or visuals that i can find yk. Tbh all i really use clients on now r blocksmc to fuck around
