### ISSUE TITLE
Client name is misleading

### ISSUE THREAD

**Issue by Kopamed** [StephenIsTaken/Raven-BPlusPlusPlus#5]
Your addition, and improvement of a client is appreciated, but please don't give it a misleading name like "Raven B4" as this is obviously not. Raven B4 will be released by blowsy, the actual developer of b1,b2,b3, and b4. Trying to get those clicks from google by using the name Raven B4 will probably only get you hate.

**Comment by StephenIsTaken** [comment]
> Your addition, and improvement of a client is appreciated, but please don't give it a misleading name like "Raven B4" as this is obviously not. Raven B4 will be released by blowsy, the actual developer of b1,b2,b3, and b4. Trying to get those clicks from google by using the name Raven B4 will probably only get you hate. 

What lmfao, what is kopamed doin here. The name b4 is a obvious joke that kinda everyone in blowsy server knows about.(by everyone i mean active ppl) but its probably a good ides to change it

**Comment by StephenIsTaken** [comment]
Also just wondering do you just search github for raven skids or did someone send this to you?

**Comment by Cosmic-SC** [comment]
ahhhhhhhhhhhhhhh steveeeeeeeeeeee change itttttttttttttt

**Comment by Cosmic-SC** [comment]
> > Your addition, and improvement of a client is appreciated, but please don't give it a misleading name like "Raven B4" as this is obviously not. Raven B4 will be released by blowsy, the actual developer of b1,b2,b3, and b4. Trying to get those clicks from google by using the name Raven B4 will probably only get you hate.
> 
> What lmfao, what is kopamed doin here. The name b4 is a obvious joke that kinda everyone in blowsy server knows about.(by everyone i mean active ppl) but its probably a good ides to change it

change to b+++

**Comment by StephenIsTaken** [comment]
> lmfao

**Comment by StephenIsTaken** [comment]
> change to b+++

Lmfao

**Comment by StephenIsTaken** [comment]
Uhmm ok ig

**Comment by Cosmic-SC** [comment]
change repo name already tbh its not really a joke now

**Comment by StephenIsTaken** [comment]
> change repo name already tbh its not really a joke now

Say a random letter

**Comment by Cosmic-SC** [comment]
brr b+++ betor
