### ISSUE TITLE
Aura

### ISSUE THREAD

**Issue by Darkmonkey55** [StephenIsTaken/Raven-BPlusPlusPlus#8]
**Describe the bug**
I have someone added on friends but when I turned off target friends in target category killaura stil targetted them
**To Reproduce**
Toggle killaura, 
add someone as a friend
turn off target for friends
and test it... idk if it always happens but has done for like 20 mins consistently.

**Expected behavior**
I would expect it to not attack friends because well yk thats dumb
**Screenshots**
No screen shots sorry
**Desktop (please complete the following information):**
 - OS: windows
 - Browser uhm? chrome ig idk why u need to know tho
 - Version of Raven latest one i cba to check but it is the latest

**Additional context**
Uhhh cant think  of any but love the client and the legitaura is so good for every server, maybe make a cps mod for it so that you can see cps because other mods dont count that sort of cps. Also I would LOVE for this to be able to inject into lunar with weave client it would genuinely make life so much easier xD.

**Comment by Darkmonkey55** [comment]
it is the v1.1 latest version from 2 days ago

**Comment by Cosmic-SC** [comment]
legitaura?

**Comment by Cosmic-SC** [comment]
also the target friends does not target MCF friends NOT /friend friends

**Comment by Cosmic-SC** [comment]
and also idk weave so no weave/lunar for the foreseeable future

**Comment by Darkmonkey55** [comment]
> legitaura?

By legit aura i meant the killaura with the legitattack settings but i suppose all killaura does.

The target friends doesnt stop you hitting people you did friends add <name> in the terminal in gui?? if not then you should add that because it would be useful

Weaveloader is kinda newish but it is wellknown now, b++ is on weave mostly and so is smok client and fractal client and lots of other mods. You can search ravenweave on github or youtube or smok client by sleepyfish and see how it works. It would be useful and i reckon more people would download b+++ if it was injecting into lunar, but it is your choice.

**Comment by StephenIsTaken** [comment]
> > legitaura?
> 
> By legit aura i meant the killaura with the legitattack settings but i suppose all killaura does.
> 
> The target friends doesnt stop you hitting people you did friends add <name> in the terminal in gui?? if not then you should add that because it would be useful
> 
> Weaveloader is kinda newish but it is wellknown now, b++ is on weave mostly and so is smok client and fractal client and lots of other mods. You can search ravenweave on github or youtube or smok client by sleepyfish and see how it works. It would be useful and i reckon more people would download b+++ if it was injecting into lunar, but it is your choice.

He knows what weave is dont worry

**Comment by Cosmic-SC** [comment]
> > > legitaura?
> > 
> > 
> > By legit aura i meant the killaura with the legitattack settings but i suppose all killaura does.
> > The target friends doesnt stop you hitting people you did friends add  in the terminal in gui?? if not then you should add that because it would be useful
> > Weaveloader is kinda newish but it is wellknown now, b++ is on weave mostly and so is smok client and fractal client and lots of other mods. You can search ravenweave on github or youtube or smok client by sleepyfish and see how it works. It would be useful and i reckon more people would download b+++ if it was injecting into lunar, but it is your choice.
> 
> He knows what weave is dont worry

idk how weave works

**Comment by Cosmic-SC** [comment]
> > legitaura?
> 
> By legit aura i meant the killaura with the legitattack settings but i suppose all killaura does.
> 
> The target friends doesnt stop you hitting people you did friends add in the terminal in gui?? if not then you should add that because it would be useful
> 
> Weaveloader is kinda newish but it is wellknown now, b++ is on weave mostly and so is smok client and fractal client and lots of other mods. You can search ravenweave on github or youtube or smok client by sleepyfish and see how it works. It would be useful and i reckon more people would download b+++ if it was injecting into lunar, but it is your choice.

legit attack is just an autoclicker that u cannot use to vanilla autoblock with
and also i just learned that friends system is broken in b++ so ill have to look into that

**Comment by Cosmic-SC** [comment]
alright I can finally look into the issue

**Comment by Darkmonkey55** [comment]
ok cool thanks!

**Comment by Cosmic-SC** [comment]
> **Describe the bug** I have someone added on friends but when I turned off target friends in target category killaura stil targetted them **To Reproduce** Toggle killaura, add someone as a friend turn off target for friends and test it... idk if it always happens but has done for like 20 mins consistently.
> 
> **Expected behavior** I would expect it to not attack friends because well yk thats dumb **Screenshots** No screen shots sorry **Desktop (please complete the following information):**
> 
> * OS: windows
> * Browser uhm? chrome ig idk why u need to know tho
> * Version of Raven latest one i cba to check but it is the latest
> 
> **Additional context** Uhhh cant think of any but love the client and the legitaura is so good for every server, maybe make a cps mod for it so that you can see cps because other mods dont count that sort of cps. Also I would LOVE for this to be able to inject into lunar with weave client it would genuinely make life so much easier xD.

Hey! I've looked at this issue and the friends system seems to work fine, just use Middle Click to add/remove friends its much better and convenient

**Comment by Cosmic-SC** [comment]
everything is done ✅

**Comment by Darkmonkey55** [comment]
friends system kinda works but whne i try to remove friends by doin friends remove <name> in the terminal it crashes

**Comment by Cosmic-SC** [comment]
use Middle Click to remove friends coz terminal command is broken. If you use the command now it wont crash but will give  u an error

**Comment by Cosmic-SC** [comment]
> > > **Describe the bug** I have someone added on friends but when I turned off target friends in target category killaura stil targetted them **To Reproduce** Toggle killaura, add someone as a friend turn off target for friends and test it... idk if it always happens but has done for like 20 mins consistently.
> > > **Expected behavior** I would expect it to not attack friends because well yk thats dumb **Screenshots** No screen shots sorry **Desktop (please complete the following information):**
> > > 
> > > * OS: windows
> > > * Browser uhm? chrome ig idk why u need to know tho
> > > * Version of Raven latest one i cba to check but it is the latest
> > > 
> > > **Additional context** Uhhh cant think of any but love the client and the legitaura is so good for every server, maybe make a cps mod for it so that you can see cps because other mods dont count that sort of cps. Also I would LOVE for this to be able to inject into lunar with weave client it would genuinely make life so much easier xD.
> > 
> > 
> > Hey! I've looked at this issue and the friends system seems to work fine, just use Middle Click to add/remove friends its much better and convenient
> 
> uhh when i turned middle click on for add friend and middle clicked people it didnt do anything there werent messages in chat or like anything? how do i know if they are added as a friend. Also if i add as a friend and turn off target friends in aura will they get targetted still?

change mode to addFriend/removeFriend

**Comment by Darkmonkey55** [comment]
tf where is that?
